### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by Aspect1103** [ThaTiemsz/Discord-Emoji-Downloader#10]
When I am trying to download the emojis, some servers work. But others return a type error.

Can this be sorted please.

**Comment by ThaTiemsz** [comment]
Could you send a screenshot of the TypeError?

**Comment by ThaTiemsz** [comment]
I've pushed some changes. Does this issue still occur for you with the new changes?

**Comment by Aspect1103** [comment]
It works now. Thanks!
