### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Ramzh** [ThaTiemsz/Discord-Emoji-Downloader#11]
It stays here and keeps loading
![image](https://user-images.githubusercontent.com/20802073/83411359-fe87d180-a40f-11ea-8a31-3c8792e97810.png)

Any help?

**Comment by ThaTiemsz** [comment]
Hmm, it seems to work fine for me. What browser are you using?

**Comment by Ramzh** [comment]
> 
> 
> Hmm, it seems to work fine for me. What browser are you using?

Currently using Firefox Quantum 77.0.1

**Comment by ThaTiemsz** [comment]
I've just tested it on the same browser and version and it still works for me. If you open the console (Ctrl + Shift + I), do you get any errors?

**Comment by Ramzh** [comment]
> 
> 
> I've just tested it on the same browser and version and it still works for me. If you open the console (Ctrl + Shift + I), do you get any errors?

I do actually:
![image](https://user-images.githubusercontent.com/20802073/83975297-10bfaf00-a8eb-11ea-888d-50305f760552.png)

**Comment by ThaTiemsz** [comment]
Try hard reloading the page by doing Ctrl + Shift + R. Does the error still occur after doing this?

**Comment by Ramzh** [comment]
> 
> 
> Try hard reloading the page by doing Ctrl + Shift + R. Does the error still occur after doing this?

Found the culprit. It's Privacy Badger. Disabling makes it work! Sorry for wasting your time man! Thanks for the help and it works!
