### ISSUE TITLE
?

### ISSUE THREAD

**Issue by kac4ebc** [ThaTiemsz/Discord-Emoji-Downloader#12]

**Comment by ThaTiemsz** [comment]
What's your issue?

**Comment by Johnny165** [comment]
The downloader does not work anymore :/

**Comment by Johnny165** [comment]
is there any way this could be fixed?

**Comment by ThaTiemsz** [comment]
@Johnny165 I'm going to look into it.

**Comment by Johnny165** [comment]
Oh ok, thank you very much, I really appreciate it 👍

**Comment by ThaTiemsz** [comment]
@Johnny165 It seems to be working fine on my end. If you open up the Dev Tools by pressign F12, do you see any errors in the console?

**Comment by Johnny165** [comment]
@ThaTiemsz That's odd, maybe its a FireFox issue? It shows this:
![Screen Shot 2020-06-25 at 9 05 44 PM](https://user-images.githubusercontent.com/29667895/85810004-af3f7300-b727-11ea-9b79-337cf65d790f.jpg)

**Comment by Johnny165** [comment]
Yeah, it seems to be an issue with FireFox for some reason... it works fine on another browser, thank you.

**Comment by ThaTiemsz** [comment]
@Johnny165 Is it possible that you have the PrivacyBadger extension enabled? Another person found that this was the culprit (https://github.com/ThaTiemsz/Discord-Emoji-Downloader/issues/11#issuecomment-640263301)

**Comment by Johnny165** [comment]
oh, that makes sense... yeah, I had Privacy Badger on. No wonder why it was causing that issue Lol. I think this should be as a warning for the ReadMe only if you can add it at this time.

**Comment by Johnny165** [comment]
Anyways, thank you very much for the help, I appreciate it. This program is awesome 👍
