### ISSUE TITLE
A better documentaion?

### ISSUE THREAD

**Issue by Chkoupinator** [ThaTiemsz/Discord-Emoji-Downloader#2]
I'm sorry but I really don't get how I'm supposed to make a GET request to https://discordapp.com/api/v6/guilds/<server id> I have the server ID but how do I make said GET request?

**Comment by ThaTiemsz** [comment]
I've come up with a little redesign with additional features just now, which I might work on in the next couple days and it should make the process a lot easier.

**Comment by ThaTiemsz** [comment]
@Chkoupinator New update is out, the tool should be way easier to use now!

**Comment by Chkoupinator** [comment]
the [?] button that is supposed to show how to get one's token is broken :/

**Comment by ThaTiemsz** [comment]
@Chkoupinator What browser and OS are you using?

**Comment by ThaTiemsz** [comment]
@Chkoupinator Should be fixed now. Make sure you hard reload (Ctrl + Shift + R), cause GitHub can be slow to update sites.
