### ISSUE TITLE
Downloaded images aren't actual images

### ISSUE THREAD

**Issue by M1ntoh** [ThaTiemsz/Discord-Emoji-Downloader#3]
Don't know if this is still being supported saw you made a commit 17 days ago. Anyway once the zip is downloaded the images error out when opening with default photo viewer in windows 10 you get 
"It looks like we don't support this file format."
This happens on all the servers I've tried it one (even ones I've previously downloaded).

**Comment by ThaTiemsz** [comment]
Thanks for bringing this to my attention, it has now been fixed.
