### ISSUE TITLE
aggregating the zip file only packs broken images

### ISSUE THREAD

**Issue by Draic** [ThaTiemsz/Discord-Emoji-Downloader#33]
Everything works until packing the emoji's into a zip and downloading that. All files in the zip are 28bytes long and opening them in an editor shows the following text: "See /corsdemo for more info"

**Comment by cmod31** [comment]
same issue

**Comment by Windfine-Github** [comment]
same

**Comment by ThaTiemsz** [comment]
Fixed with #51
