### ISSUE TITLE
Updated version for stealing stickers

### ISSUE THREAD

**Issue by Nepahlem** [ThaTiemsz/Discord-Emoji-Downloader#37]
As the title states is it possible to add stealing stickers as well?

**Comment by lukasong** [comment]
Did you ever find an alternative solution for grabbing stickers? @Nepahlem

**Comment by Nepahlem** [comment]
Sadly not yet

**Comment by BiffBish** [comment]
https://biffbish.github.io/Discord-Emoji-Downloader/
#43

**Comment by ThaTiemsz** [comment]
Sticker support has been added!
