### ISSUE TITLE
I have a bold request

### ISSUE THREAD

**Issue by sooooooooooooooooootheby** [ThaTiemsz/Discord-Emoji-Downloader#46]
I want to put this crawler tool on my website (in other words, a special collection). Of course, I'll note the author and source.
As you can see, my site is relatively empty and not live yet. I will be glad if you can agree. If not, thank you for replying to me.
![image](https://github.com/ThaTiemsz/Discord-Emoji-Downloader/assets/120046369/a950c8b5-3a6c-42fe-af95-3f76ba2c2747)

**Comment by ThaTiemsz** [comment]
Hi, sure! Feel free to add it.

**Comment by sooooooooooooooooootheby** [comment]
thank！
