### ISSUE TITLE
Downloading the emoji just redirects you to the front page

### ISSUE THREAD

**Issue by no-boot-device** [ThaTiemsz/Discord-Emoji-Downloader#5]

**Comment by Roeekush** [comment]
Having the same problem. download button just takes you back.

**Comment by ThaTiemsz** [comment]
Thanks, I'll take a look at it soon.

**Comment by ThaTiemsz** [comment]
This should be fixed now. Can you confirm it is fixed?

**Comment by Roeekush** [comment]
It is working fine for me now, thanks.
