### ISSUE TITLE
bunch of minor issues I found

### ISSUE THREAD

**Issue by Roeekush** [ThaTiemsz/Discord-Emoji-Downloader#7]
I've been trying to download all the emotes from most the servers I'm in and I've encountered a couple problems (these might be problems only for me)
1. Inputting the user token and clicking continue does nothing on Microsoft Edge
2. Trying to download the emojis through firefox only downloads a 0 bytes damaged file
3. In google chrome, downloading emojis from more than 1 server without refreshing the page is fucky. Sometimes it will download just the first server again, sometimes it'll attempt to download the first and second server in succession.

I've attempted to download stickers through other solutions and came to the conclusion that this project is, by far, the easiest and most convenient way to download emojis. please continue the development!

**Comment by Roeekush** [comment]
Hey, you still working on this project? :(

**Comment by ThaTiemsz** [comment]
Hey @Roeekush, I've just pushed an update that should fix all three of these issues. Can you confirm that the issues are fixed?
