### ISSUE TITLE
Doesn't seem to be working anymore

### ISSUE THREAD

**Issue by Aspect1103** [ThaTiemsz/Discord-Emoji-Downloader#9]
When I go  to look for the token, it's not there. So I used a workaround to find the token, but it just loads endlessly once I paste the token it and start it. Do you know why?

**Comment by QzyxTpik** [comment]
Same issue, discord changed their main website

**Comment by ThaTiemsz** [comment]
Thanks, I will look into it.

**Comment by ThaTiemsz** [comment]
@Aspect1103 @QzyxTpik It should be fixed now!
